### ISSUE TITLE
/snap/tizonia/131/bin/tizonia-snap-wrapper.sh: line 22:  9326 Segmentation fault

### ISSUE THREAD

**Issue by mrmodolo** [tizonia/tizonia-snap#2]
I installed the snap and edited the configuration file including my username and password for spotify.
When trying to run the command below I get a "core dumped"

~ vim /home/modolo/snap/tizonia/current/.config/tizonia/tizonia.conf 
~ tizonia --spotify-playlist list
tizonia 0.13.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Spotify] [Connecting] : 'mrmodolo'.
/snap/tizonia/131/bin/tizonia-snap-wrapper.sh: line 22:  9326 Segmentation fault      (core dumped) $SNAP/usr/bin/tizonia "$@"

Distributor ID:	Ubuntu
Description:	Ubuntu Bionic Beaver (development branch)
Release:	18.04
Codename:	bionic

Thanks,
Marcelo Módolo

**Comment by juanrubio** [comment]
Hi!, thanks for taking the time the report this issue.

Another user has reported it in the main repo:
- https://github.com/tizonia/tizonia-openmax-il/issues/479

It looks like this is snap-specific but I'm going to keep both issues open until I know for sure.

**Comment by juanrubio** [comment]
I'm closing this issue now. The issue has been fixed in v0.14.0 (v0.14.0 is in the edge channel now).
