### ISSUE TITLE
[OMX.Aratelia.audio_source.http:port:0]  [OMX_ErrorInsufficientResources]

### ISSUE THREAD

**Issue by silvernode** [tizonia/tizonia-snap#3]
Installed the Snap on my Fedora (28) desktop and entered my credentials with the --gplay-unlimited-artist option. It worked great on the desktop but on the laptop (Fedora 28) using the Snap and the same command line input, I get  

```
[OMX.Aratelia.audio_source.http:port:0]
[OMX_ErrorInsufficientResources]
```

EDIT: To clarify, I installed using ```sudo snap install tizonia``` on both machines

**Comment by tizonia** [comment]
Hi, thanks for taking the time to report this.

Do you think there is a chance that you have not introduced your credentials in $HOME/snap/tizonia/current/.config/tizonia/tizonia.conf on your laptop?

**Comment by tizonia** [comment]
I suppose user credentials won't be the issue.

Would you be able to upload the debug logs? To generate them, here is the logging system configuration file:
[log4crc.zip](https://github.com/tizonia/tizonia-snap/files/2113061/log4crc.zip)

You need to unzip this file and copy it under:
```
$HOME/snap/tizonia/current/.log4crc
```
Thanks!

**Comment by tizonia** [comment]
FYI, version 0.15.0 is now in the snap store.

**Comment by silvernode** [comment]
I have updated and still have the same issue. I copied the log generation file to ~/snap/tizonia/current/.log4crc and now get a bunch of debug information. Should I redirect the debug information to a file or is there already a file with the error information now that I have run tizonia with debug enabled?  

EDIT: Here is the script I created to use Tizonia the way I want. This will show you how I am using it:  

https://gist.github.com/silvernode/0d1698626ec6bfc55359fdf7aecd5c67

**Comment by tizonia** [comment]
Thanks. The log4crc file I gave you contains configuration to output to console, just for convenience, but it can also be modified to output to a file. Just replace "stdout" with "tizlogfile" in this line:
```
<category name="root" priority="trace" appender="stdout"/>
```

After that, the debug info should be in a file: /tmp/tizonia.log

**Comment by silvernode** [comment]
I should be able to just >> to a file, that would be just as good right?

**Comment by tizonia** [comment]
Correct, that would be just as good.

**Comment by silvernode** [comment]
[tizonia.debug.txt](https://gist.githubusercontent.com/silvernode/767451368ac40778ad257f491bd2e82b/raw/ffd34e197c3714acb9cab2be8a488b9c30dc2fc3/tizonia.debug.txt)

**Comment by tizonia** [comment]
Thanks, I think you are setting an incorrect password in tizonia.conf.

This is what I get when I type something that is NOT my Google Music password in tizonia.conf:

```
tizonia 0.15.0. Copyright (C) 2018 Juan A. Rubio
This software is part of the Tizonia project <http://tizonia.org>

[Google Play Music] [Connecting] : 'jarubio2001_at_gmail.com'.
[Google Play Music] [Authenticating] : 'with user credentials'
[Google Play Music] [Retrieving genres] : 'jarubio2001_at_gmail.com'. 
[Google Play Music] (NotLoggedIn) : 

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

By the way, I forgot to mention that your password is displayed in the log ! (although I assume it is not the correct one...)

**Comment by silvernode** [comment]
I wonder if I still need certain gstreamer plugins even though tizonia is in a snap?

Edit, I didn't realize you replied so fast, let me check password

**Comment by silvernode** [comment]
I generated a new app password (since I use 2-factor on google) and Tizonia works now. I guess I must have not copied the full password the last time. Thanks for all your help, I will let my friend know to check his password too since he has the same error.

**Comment by tizonia** [comment]
Cool, I'm glad it works now!

**Comment by silvernode** [comment]
It might be worth considering a more clear and precise error message if possible. :+1:
