### ISSUE TITLE
tizonia.conf readable by other users

### ISSUE THREAD

**Issue by StenPett** [tizonia/tizonia-snap#7]
I noticed that by default, the snap/tizonia/.config/tizonia/tizonia.conf file is readable by all users and groups. Since this is where the usernames and passwords are stored in plain text, would it make more sense to have it only readable by the owner?

I changed mine with `chmod 600 tizonia.conf` and it seems to work as expected so far, at least with Spotify

**Comment by tizonia** [comment]
Hi @StenPett !

Thanks a lot for trying the software and for taking the time to report problems.

I completely agree that storing passwords in clear text in a configuration file is far from ideal. However, the passwords are stored manually by the user. Perhaps there should be some warnings in the configuration file to advise users to restrict access to the file. Or even a warning message could be output in the console, when Tizonia starts, as a way of nagging users to change the file mode bits.

I'll create an issue in the main repository to get something like that implemented.

**Comment by tizonia** [comment]
Closing this issue here, as it is now reported in the main repo.
