### ISSUE TITLE
pop!_OS upgrade to 20.04 broke snap tizonia

### ISSUE THREAD

**Issue by jonspraggins** [tizonia/tizonia-snap#8]
Was working fine yesterday, but now post update to Pop!_OS 20.04 I receive the following for gmusic:

```
[Google Play Music] (ConnectionError) : HTTPSConnectionPool(host='mclients.googleapis.com', port=443): Max retries exceeded with url: /sj/v2.5/devicemanagementinfo?dv=0&tier=fr&alt=json&hl=en_US (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbe9464c810>: Failed to establish a new connection: [Errno -2] Name or service not known',))

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

and I recieve this for youtube:

```
[YouTube] (URLError) : <urlopen error [Errno -2] Name or service not known>

tizonia exiting (OMX_ErrorInsufficientResources).

 [OMX.Aratelia.audio_source.http:port:0]
 [OMX_ErrorInsufficientResources]
```

**Comment by juanrubio** [comment]
Hi @jonspraggins !

Thanks for taking the time to report an issue.

Have you tried reinstalling it? 

In any case, the snap of Tizonia is currently out of date, and in need of a refresh. So it's not entirely surprising if at some point it stops working when people upgrade to fresher distros.

There is a [call for maintainers](https://github.com/tizonia/tizonia-snap/blob/master/README.md) in this repo in case someone from the community would like to step up and help with the maintenance of the snap package.

**Comment by jonspraggins** [comment]
Noted.  I'm not the biggest fan of snap.  I'd rather expand the normal installer to support Pop!_OS (it's honestly ubuntu at it's core).

**Comment by juanrubio** [comment]
> expand the normal installer to support Pop!_OS

Please feel free to submit a PR in the main repo. The installer just needs to be told which Ubuntu-like distro names are supported. 

See:
https://github.com/tizonia/tizonia-openmax-il/blob/master/tools/install.sh#L75



Note that there are not Focal binaries yet (will be when 0.22.0 comes out, not too far from now).

**Comment by jonspraggins** [comment]
focal should work, I hope:

```
jspraggins@silver76:~$ cat /etc/*-release | grep focal
DISTRIB_CODENAME=focal
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by juanrubio** [comment]
@jonspraggins 

FYI, Tizonia 0.22.0 has been released. Ubuntu Focal binaries are available.

**Comment by jonspraggins** [comment]
Exciting news!  Thank you for your work @juanrubio.  You should have a place to accept donations somewhere on your site.

**Comment by juanrubio** [comment]
> accept donations somewhere on your site.

Thanks for the suggestion. Don't forget to give your star in any of the repos. That alone would mean a lot! ;-)

**Comment by juanrubio** [comment]
The Snap package has been refreshed and now it is at version 0.22.0. 

So I'm closing this issue for now.
